\i 'C:\\Users\\titan\\Documents\\Projects\\My-Repository-S3\\PROG3\\Restaurant-v2\\src\\main\\java\\com\\titan\\db\\migration\\0_create_db.sql'
\i 'C:\\Users\\titan\\Documents\\Projects\\My-Repository-S3\\PROG3\\Restaurant-v2\\src\\main\\java\\com\\titan\\db\\migration\\1_create_table_dish.sql'
\i 'C:\\Users\\titan\\Documents\\Projects\\My-Repository-S3\\PROG3\\Restaurant-v2\\src\\main\\java\\com\\titan\\db\\migration\\2_create_table_ingredient.sql'
\i 'C:\\Users\\titan\\Documents\\Projects\\My-Repository-S3\\PROG3\\Restaurant-v2\\src\\main\\java\\com\\titan\\db\\migration\\3_create_table_ingredient_price.sql'
\i 'C:\\Users\\titan\\Documents\\Projects\\My-Repository-S3\\PROG3\\Restaurant-v2\\src\\main\\java\\com\\titan\\db\\migration\\4_create_table_dish_ingredient.sql'
\i 'C:\\Users\\titan\\Documents\\Projects\\My-Repository-S3\\PROG3\\Restaurant-v2\\src\\main\\java\\com\\titan\\db\\migration\\5_create_tables_stocks.sql'
\i 'C:\\Users\\titan\\Documents\\Projects\\My-Repository-S3\\PROG3\\Restaurant-v2\\src\\main\\java\\com\\titan\\db\\migration\\6_create_table_order.sql'
\i 'C:\\Users\\titan\\Documents\\Projects\\My-Repository-S3\\PROG3\\Restaurant-v2\\src\\main\\java\\com\\titan\\db\\migration\\7_create_table_order_status.sql'
\i 'C:\\Users\\titan\\Documents\\Projects\\My-Repository-S3\\PROG3\\Restaurant-v2\\src\\main\\java\\com\\titan\\db\\migration\\8_create_table_dish_order.sql'
\i 'C:\\Users\\titan\\Documents\\Projects\\My-Repository-S3\\PROG3\\Restaurant-v2\\src\\main\\java\\com\\titan\\db\\migration\\9_create_table_dish_order_status.sql'
-- \i 'C:\\Users\\titan\\Documents\\Projects\\My-Repository-S3\\PROG3\\Restaurant-v2\\src\\main\\java\\com\\titan\\db\\migration\\migration_runner.sql'
